const transactions = [
  {
    id: 'tx_001',
    title: 'Grocery Shopping',
    description: 'Bought rice, milk, and eggs at Shoprite',
    category: 'Groceries',
    amount: 45.75,
    type: 'expense',
    date: '2025-10-02T14:35:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_002',
    title: 'Freelance Payment',
    description: 'Received payment for website design project',
    category: 'Income',
    amount: 250.0,
    type: 'income',
    date: '2025-10-03T09:15:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_003',
    title: 'Electricity Bill',
    description: 'Prepaid electricity recharge',
    category: 'Utilities',
    amount: 28.4,
    type: 'expense',
    date: '2025-10-04T08:10:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_004',
    title: 'Data Subscription',
    description: 'MTN 10GB monthly plan',
    category: 'Internet',
    amount: 8.2,
    type: 'expense',
    date: '2025-10-05T10:25:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_005',
    title: 'Fuel Refill',
    description: 'Filled car tank at NNPC station',
    category: 'Transport',
    amount: 35.0,
    type: 'expense',
    date: '2025-10-06T07:50:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_006',
    title: 'Coffee at Café Neo',
    description: 'Morning coffee and croissant',
    category: 'Food & Drink',
    amount: 6.25,
    type: 'expense',
    date: '2025-10-07T08:45:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_007',
    title: 'Gym Subscription',
    description: 'Monthly payment for gym membership',
    category: 'Fitness',
    amount: 30.0,
    type: 'expense',
    date: '2025-10-08T17:00:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_008',
    title: 'Uber Ride',
    description: 'Trip from Yaba to Lekki',
    category: 'Transport',
    amount: 12.0,
    type: 'expense',
    date: '2025-10-09T13:20:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_009',
    title: 'Netflix Subscription',
    description: 'Monthly streaming plan',
    category: 'Entertainment',
    amount: 9.99,
    type: 'expense',
    date: '2025-10-10T18:00:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_010',
    title: 'Salary',
    description: 'October salary payment',
    category: 'Income',
    amount: 1200.0,
    type: 'income',
    date: '2025-10-10T09:00:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_011',
    title: 'Airtime Purchase',
    description: 'Airtime for calls and SMS',
    category: 'Utilities',
    amount: 3.5,
    type: 'expense',
    date: '2025-10-11T12:30:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_012',
    title: 'Book Purchase',
    description: 'Bought JavaScript reference book',
    category: 'Education',
    amount: 15.0,
    type: 'expense',
    date: '2025-10-12T11:00:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_013',
    title: 'Online Course',
    description: 'Enrolled in React.js advanced course',
    category: 'Education',
    amount: 39.99,
    type: 'expense',
    date: '2025-10-13T15:30:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_014',
    title: 'Sold Old Laptop',
    description: 'Sold my old HP Pavilion laptop',
    category: 'Income',
    amount: 350.0,
    type: 'income',
    date: '2025-10-14T16:10:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_015',
    title: 'Haircut',
    description: 'Trimmed at Signature Cuts barbershop',
    category: 'Personal Care',
    amount: 5.5,
    type: 'expense',
    date: '2025-10-15T13:00:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_016',
    title: 'Dinner Date',
    description: 'Dinner at Yellow Chilli Restaurant',
    category: 'Food & Drink',
    amount: 60.0,
    type: 'expense',
    date: '2025-10-16T20:30:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_017',
    title: 'Sold Graphic Design',
    description: 'Payment for logo design project',
    category: 'Income',
    amount: 80.0,
    type: 'income',
    date: '2025-10-17T19:00:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_018',
    title: 'Medical Checkup',
    description: 'General body checkup at health center',
    category: 'Health',
    amount: 25.0,
    type: 'expense',
    date: '2025-10-18T10:00:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_019',
    title: 'Bought Sneakers',
    description: 'New Nike Air Max sneakers',
    category: 'Shopping',
    amount: 85.0,
    type: 'expense',
    date: '2025-10-19T17:20:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_020',
    title: 'YouTube Premium',
    description: 'Monthly ad-free subscription',
    category: 'Entertainment',
    amount: 11.99,
    type: 'expense',
    date: '2025-10-20T08:00:00Z',
    imageUrl: '',
  },
  // 👇 this week (Oct 21–23)
  {
    id: 'tx_021',
    title: 'Groceries at Market Square',
    description: 'Bought vegetables, fruits, and bread',
    category: 'Groceries',
    amount: 32.6,
    type: 'expense',
    date: '2025-10-21T09:10:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_022',
    title: 'Client Invoice Payment',
    description: 'Received project balance from client',
    category: 'Income',
    amount: 400.0,
    type: 'income',
    date: '2025-10-21T15:20:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_023',
    title: 'Taxi Ride to Office',
    description: 'Bolt trip to coworking space',
    category: 'Transport',
    amount: 5.75,
    type: 'expense',
    date: '2025-10-22T08:30:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_024',
    title: 'Bought Airtime',
    description: 'Recharge for calls and data',
    category: 'Utilities',
    amount: 3.0,
    type: 'expense',
    date: '2025-10-22T19:45:00Z',
    imageUrl: '',
  },
  // 👇 today (Oct 23)
  {
    id: 'tx_025',
    title: 'Breakfast at Café',
    description: 'Egg sandwich and cappuccino',
    category: 'Food & Drink',
    amount: 7.25,
    type: 'expense',
    date: '2025-10-23T08:15:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_026',
    title: 'App Hosting Renewal',
    description: 'Renewed Vercel hosting plan',
    category: 'Subscription',
    amount: 20.0,
    type: 'expense',
    date: '2025-10-23T10:05:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_027',
    title: 'UI Design Sale',
    description: 'Sold mobile UI design pack on Gumroad',
    category: 'Income',
    amount: 60.0,
    type: 'income',
    date: '2025-10-23T11:50:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_028',
    title: 'Lunch Takeout',
    description: 'Jollof rice with grilled chicken',
    category: 'Food & Drink',
    amount: 10.5,
    type: 'expense',
    date: '2025-10-23T13:40:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_029',
    title: 'Online Donation',
    description: 'Supported a friend’s fundraiser',
    category: 'Charity',
    amount: 15.0,
    type: 'expense',
    date: '2025-10-23T16:10:00Z',
    imageUrl: '',
  },
  {
    id: 'tx_030',
    title: 'Sold Plugin',
    description: 'Received payment for custom VS Code plugin',
    category: 'Income',
    amount: 120.0,
    type: 'income',
    date: '2025-10-23T18:20:00Z',
    imageUrl: '',
  },
];

export default transactions;
